### ISSUE TITLE
problem with android studio 2.2.1

### ISSUE THREAD

**Issue by zeevchippc** [red5pro/android-streaming-testbed#15]
Dear all,

i tried to compile the software, but get an error:
Error Note: /Users/zeevmindali/Desktop/streamer/app/src/main/java/red5pro/org/testandroidproject/tests/SubscribeImageTest/SubscribeImageTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:compileDebugJavaWithJavac'.
  
  > java.io.FileNotFoundException: /Users/zeevmindali/Desktop/streamer/app/libs/red5pro-1.0.2.jar (No such file or directory)
- Try:
  Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

**Comment by beetlejesss** [comment]
I have been building this successfully using Studio v2.2. Just upgraded to 2.2.2, and also was able to build successfully. 
If you are prompted to upgrade the gradle version when you open this project, do not do so.
